(defvar :smallfont-name "6x10")

(unless (boundp ':smallfont)
        (defvar :smallfont))

(defvar :curve-user-action (lambda (b ev) ()))

(de courbe2d (curve dx dy kx ky)
    (let* ((body (get-slot-value curve 'body))
           (n (vlength body))
           (vx (makevector n 0))
           (vy (makevector n 0)))
      (for (i 0 1 (sub1 n))
           (vset vx i (fix (* kx (- (car (vref body i)) dx))))
           (vset vy i (fix (* ky (- (cadr (vref body i)) dy)))))
      (omakeq {polyline} n n vx vx vy vy)))

(de droitetechnique (x0 x1 curve dx dy kx ky)
    (let ((pente (get-slot-value curve 'pente))
          (ordonnee (get-slot-value curve 'ordonnee-zero)))
      (omakeq {polyline}
              n 2
              vx (vector (fix (* kx (- x0 dx)))
                         (fix (* kx (- x1 dx))))
              vy (vector (fix (* ky (- (+ ordonnee (* x0 pente)) dy)))
                         (fix (* ky (- (+ ordonnee (* x1 pente)) dy)))))))

(de lignebrisee (curve dx dy kx ky)
    (let* ((liste (get-slot-value curve 'liste-de-points))
           (n (length liste))
           (vx (makevector n 0))
           (vy (makevector n 0)))
      (for (i 0 1 (sub1 n))
           (vset vx i (fix (* kx (- (car (car liste)) dx))))
           (vset vy i (fix (* ky (- (cadr (nextl liste)) dy)))))
      (omakeq {polyline} n n vx vx vy vy)))

(de :repeater (i)
    (repeater
     (:fond-blanc
     (font :bigfont
           (translation 1 1
                        (boxedview
                         (:double-bbox
                          (mul :button-widthcn #wc)
                          (add 8 #hc)
                          (translation 0 1 i))))))))

(defvar *glue* 10)
(defvar *space* 4)

(defabbrev curveapplication {Application}:curveapplication)

(defstruct {curveapplication}
  editor scalex scaley transx transy step index scale x1 x2)

(setq #:sys-package:colon '{curveapplication})

(defvar :rectangle #:image:rectangle:#[0 0 0 0])

(de curveappli (w1 h1 curves)
    (unless #:user:smallfont
	    (setq #:user:smallfont (load-font #:user:smallfont-name)))
    (let* ((scale (:get-scale-bbox (get-slot-value (car curves) 'body)
                                   :rectangle))
           (index 0)
           (step 10)
           (x1 ({rectangle}:x :rectangle))
           (y1 (- ({rectangle}:y :rectangle) *glue*))
           (x2 ({rectangle}:w :rectangle))
           (y2 (+ ({rectangle}:h :rectangle) *glue*))
           (comment (application '{application} 0 0
				 (mul 10
				       (with ((current-font #:user:smallfont))
					     (width-space)))
				 (mul 2
				       (with ((current-font #:user:smallfont))
					     (height-space)))
				 (font #:user:smallfont 
				       (column
					(catenate " x="
						  (string
						   (car (vref scale index))))
					(catenate " y="
						  (string
						   (cadr (vref scale index)))))
				       )))
           (fast (#:user:repeater " FAST "))
           (slow (#:user:repeater " SLOW "))
           (mark (#:user:repeater " Mark "))
           (user (#:user:repeater " User "))
           (w2 (div (sub w1 (add (send 'width comment)
                                 (add (send 'width mark)
                                      (add (send 'width user)
                                           (add (send 'width slow)
                                                (send 'width fast))))))
                    2))
           (glue1 (rectangle 0 0 w2 0))
           (glue2 (rectangle 0 0 w2 0))
           (panel (row comment glue1 mark user glue2 slow fast))
           (curvexmax w1)
           (curveymax (sub h1 (send 'height panel)))
           (dx x1)
           (dy y1)
           (kx (/ curvexmax (- x2 x1)))
           (ky (/ curveymax (- y2 y1)))
           (w  (add1 (fix (* kx (- x2 x1)))))
           (h  (fix (* ky (- y2 y1))))
           (cursor (cursor 0 0 w h))
           (images (progn (setq dy y2)
                          (setq ky (- ky))
                          (mapcar (lambda (c)
                                    (cond ((is-a c 'ligne-brisee)
                                           (lignebrisee c dx dy kx ky))
                                          ((is-a c 'courbe-2d)
                                           (courbe2d c dx dy kx ky))
                                          ((is-a c 'droite-technique)
                                           (droitetechnique x1 x2 c
                                                            dx dy kx ky))))
                                  curves)))
           (curveeditor (application '{curveeditor} 0 0 w h
                                     (apply 'view (cons cursor images))))
           (appli (application '{curveApplication} 0 0 0 0 
                               (column curveeditor panel))))
      (:editor appli curveeditor)
      (:scalex appli kx)
      (:scaley appli ky)
      (:transx appli dx)
      (:transy appli dy)
      (:step   appli step)
      (:index  appli index)
      (:scale  appli scale)
      (:x1 appli x1)
      (:x2 appli x2)
      (set-action fast (lambda (b ev)
                         (let ((appli (component 'appli b)))
                           (cond ((eq (#:event:detail ev) 1024)
                                  (if (gt (:index appli) 10)
                                      (:index appli
                                              (sub (:index appli)
                                                   (:step appli)))
                                    (:index appli 0))
                                  (:slide-cursor appli))
                                 ((eq (#:event:detail ev) 256)
                                  (if (lt (:index appli)
                                          (sub (vlength (:scale appli))
                                               (:step appli)))
                                      (:index appli
                                              (add (:index appli)
                                                   (:step appli)))
                                    (:index appli
                                            (sub1 (vlength (:scale appli))))) 
                                  (:slide-cursor appli))))))
      (set-action slow (lambda (b ev)
                         (let ((appli (component 'appli b)))
                           (cond ((and (eq (#:event:detail ev) 1024)
                                       (gt (:index appli) 0))
                                  (:index appli (sub (:index appli) 1))
                                  (:slide-cursor appli))
                                 ((and (eq (#:event:detail ev) 256)
                                       (lt (:index appli)
                                           (sub (vlength (:scale appli)) 1)))
                                  (:index appli (add (:index appli) 1))
                                  (:slide-cursor appli))))))
      (set-action mark (lambda (b ev)
                         (let* ((appli (component 'appli b))
                                (xy (vref (:scale appli) (:index appli)))
                                (editor (:editor appli)))
                           (send 'eventx editor
                                 (fix (* (:scalex appli)
                                         (- (car xy) (:transx appli)))))
                           (send 'eventy editor
                                 (fix (* (:scaley appli)
                                         (- (cadr xy) (:transy appli)))))
                           (send 'activated-event editor ()))))
      (set-action user #:user:curve-user-action)
      (set-action cursor (lambda (c)
                           (let* ((appli (component 'appli c))
                                  (xy (vref (:scale appli) (:index appli))))
                             (send 'set-image (component 'comment appli)
                                   (font #:user:smallfont
					 (column
					  (catenate " x=" (string (car xy)))
					  (catenate " y=" (string (cadr xy)))
					  ))))))
      (set-action curveeditor '{curveeditor}:set-the-mark)
      (add-component appli 'comment comment)
      (add-component appli 'cursor cursor)
      (add-component appli 'appli appli)
      (send 'fit-to-contents appli)
      appli))

(de :slide-cursor (appli)
    (send 'slide-to (component 'cursor appli)
          (fix (* (:scalex appli) (- (:index appli) (:transx appli))))))

(de :get-scale-bbox (body rectangle)
    (let* ((xmin 32767)
           (ymin 32767)
           (xmax 0)
           (ymax 0)
           curx cury)
      (for (i 0 1 (sub1 (vlength body)))
           (setq curx (car (vref body i)) cury (cadr (vref body i)))
           (when (gt curx xmax) (setq xmax curx))
           (when (lt curx xmin) (setq xmin curx))
           (when (gt cury ymax) (setq ymax cury))
           (when (lt cury ymin) (setq ymin cury)))      
      ({rectangle}:x rectangle xmin)
      ({rectangle}:y rectangle ymin)
      ({rectangle}:w rectangle xmax)
      ({rectangle}:h rectangle ymax)
      body))

(de :add-curve (appli curve)
    (let* ((dx (:transx appli))
	   (dy (:transy appli))
	   (kx (:scalex appli))
	   (ky (:scaley appli))
	   (x1 (:x1 appli))
	   (x2 (:x2 appli))
	   (editor (:editor appli))
	   (image (cond ((is-a curve 'ligne-brisee)
			 (lignebrisee curve dx dy kx ky))
			((is-a curve 'courbe-2d)
			 (courbe2d curve dx dy kx ky))
			((is-a curve 'droite-technique)
			 (droitetechnique x1 x2 curve dx dy kx ky)))))
      (send 'add-image editor image)
      (send 'redisplay editor ())))

