aidadir=/udd/chatelet/work/aida
aidadirs=${aidadir}/system/ ${aidadir}/structure/ ${aidadir}/image/ ${aidadir}/application/ ${aidadir}/library/



# Le Header commun a` tous les Makefile des modules
# pour compiler les modules
.SUFFIXES:.lo .lm
.lm.lo: ; $(COMPLICE) $* $(COMPLICEFLAGS)

COMPLICE=/udd/chatelet/distribution/v15.21/sun/complice
COMPLICEFLAGS=-e "(load \"`cd /udd/chatelet/work/aida ; pwd`/system/include.ll\")" \
	-e "(setq #:system:path (append '(${aidadirs}) #:system:path))" \
	-e "(rmargin 254)"



# This was generated by michel

all: beau-cadre.lo dates.lo points.lo courbes.lo echelles.lo mybutton.lo pres.lo voyeur.lo vue.lo bars.lo

beau-cadre.lo: beau-cadre.lm beau-cadre.lh beau-cadre.ll

dates.lo: dates.lm dates.lh dates.ll

points.lo: points.lm points.lh points.ll

courbes.lo: courbes.lm points.lh courbes.lh courbes.ll

echelles.lo: echelles.lm dates.lh courbes.lh echelles.lh echelles.ll

mybutton.lo: mybutton.lm mybutton.lh mybutton.ll

pres.lo: pres.lm courbes.lh pres.lh pres.ll

voyeur.lo: voyeur.lm /udd/chatelet/work/aida/image/image.lh /udd/chatelet/work/aida/application/application.lh voyeur.lh voyeur.ll

vue.lo: vue.lm /udd/chatelet/work/aida/image/image.lh /udd/chatelet/work/aida/application/application.lh vue.lh vue.ll

bars.lo: bars.lm courbes.lh bars.lh bars.ll

done: all; @touch all done
